CREATE DATABASE IF NOT EXISTS presupuestos_operativos;
USE presupuestos_operativos;
CREATE TABLE `rh_unidad_org`(
	`sys_pk` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`sys_guid` VARCHAR(32) NOT NULL UNIQUE,
	`sys_dtcreated` DATETIME NOT NULL,
	`sys_timestamp` DATETIME NOT NULL,
	`sys_info` VARCHAR(32),
	`sys_user` VARCHAR(32),
	`sys_lastuser` VARCHAR(32),
	`sys_exported` BOOL,
	`sys_dtexported` DATETIME,
	`sys_recver` INT,
	`sys_deleted` BOOL,
	`sys_lock` INT,
	`codigo` VARCHAR(32) NOT NULL UNIQUE,
	`descripcion` VARCHAR(150) NOT NULL,
	`superior` INT,
	`notas` VARCHAR(4096),
	`link` VARCHAR(1024)
);
CREATE TABLE `divisa`(
	`sys_pk` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`sys_guid` VARCHAR(32) NOT NULL UNIQUE,
	`sys_dtcreated` DATETIME NOT NULL,
	`sys_timestamp` DATETIME NOT NULL,
	`sys_info` VARCHAR(32),
	`sys_user` VARCHAR(32),
	`sys_lastuser` VARCHAR(32),
	`sys_exported` BOOL,
	`sys_dtexported` DATETIME,
	`sys_recver` INT,
	`sys_deleted` BOOL,
	`sys_lock` INT,
	`codigo` VARCHAR(5) NOT NULL UNIQUE,
	`descripcion` VARCHAR(30) NOT NULL,
	`tcambio` DECIMAL(18,8)
);
CREATE TABLE `gop_presupuesto_status`(
	`id` INT NOT NULL PRIMARY KEY,
	`const` VARCHAR(150)
);
CREATE TABLE `gop_presupuesto`(
	`sys_pk` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`sys_guid` VARCHAR(32) NOT NULL UNIQUE,
	`sys_dtcreated` DATETIME NOT NULL,
	`sys_timestamp` DATETIME NOT NULL,
	`sys_info` VARCHAR(32),
	`sys_user` VARCHAR(32),
	`sys_lastuser` VARCHAR(32),
	`sys_exported` BOOL,
	`sys_dtexported` DATETIME,
	`sys_recver` INT,
	`sys_deleted` BOOL,
	`sys_lock` INT,
	`ref_unidad` INT NOT NULL,
	`ejercicio` INT NOT NULL,
	`titulo` VARCHAR(150) NOT NULL,
	`notas` TEXT,
	`status` INT NOT NULL,
	`divisa` INT NOT NULL,
	`monto_autorizado` DECIMAL(18,4),
	`monto_planeado` DECIMAL(18,4),
	`monto_comprometido` DECIMAL(18,4),
	`monto_ejercido` DECIMAL(18,4)
);
CREATE TABLE `gop_partida`(
	`sys_pk` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`sys_guid` VARCHAR(32) NOT NULL UNIQUE,
	`sys_dtcreated` DATETIME NOT NULL,
	`sys_timestamp` DATETIME NOT NULL,
	`sys_info` VARCHAR(32),
	`sys_user` VARCHAR(32),
	`sys_lastuser` VARCHAR(32),
	`sys_exported` BOOL,
	`sys_dtexported` DATETIME,
	`sys_recver` INT,
	`sys_deleted` BOOL,
	`sys_lock` INT,
	`ref_presupuesto` INT NOT NULL,
	`id` VARCHAR(36) NOT NULL,
	`padre` INT,
	`partida` VARCHAR(255) NOT NULL,
	`ccontable` VARCHAR(32),
	`autorizado` DECIMAL(18,4),
	`reserva` DECIMAL(18,4),
	`p01` DECIMAL(18,4),
	`p02` DECIMAL(18,4),
	`p03` DECIMAL(18,4),
	`p04` DECIMAL(18,4),
	`p05` DECIMAL(18,4),
	`p06` DECIMAL(18,4),
	`p07` DECIMAL(18,4),
	`p08` DECIMAL(18,4),
	`p09` DECIMAL(18,4),
	`p10` DECIMAL(18,4),
	`p11` DECIMAL(18,4),
	`p12` DECIMAL(18,4),
	`rc` DECIMAL(18,4),
	`c01` DECIMAL(18,4),
	`c02` DECIMAL(18,4),
	`c03` DECIMAL(18,4),
	`c04` DECIMAL(18,4),
	`c05` DECIMAL(18,4),
	`c06` DECIMAL(18,4),
	`c07` DECIMAL(18,4),
	`c08` DECIMAL(18,4),
	`c09` DECIMAL(18,4),
	`c10` DECIMAL(18,4),
	`c11` DECIMAL(18,4),
	`c12` DECIMAL(18,4),
	`re` DECIMAL(18,4),
	`e01` DECIMAL(18,4),
	`e02` DECIMAL(18,4),
	`e03` DECIMAL(18,4),
	`e04` DECIMAL(18,4),
	`e05` DECIMAL(18,4),
	`e06` DECIMAL(18,4),
	`e07` DECIMAL(18,4),
	`e08` DECIMAL(18,4),
	`e09` DECIMAL(18,4),
	`e10` DECIMAL(18,4),
	`e11` DECIMAL(18,4),
	`e12` DECIMAL(18,4),
	`notas` TEXT
);
CREATE TABLE `gop_usuario_uo`(
	`sys_pk` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`sys_guid` VARCHAR(32) NOT NULL UNIQUE,
	`sys_dtcreated` DATETIME NOT NULL,
	`sys_timestamp` DATETIME NOT NULL,
	`sys_info` VARCHAR(32),
	`sys_user` VARCHAR(32),
	`sys_lastuser` VARCHAR(32),
	`sys_exported` BOOL,
	`sys_dtexported` DATETIME,
	`sys_recver` INT,
	`sys_deleted` BOOL,
	`sys_lock` INT,
	`ref_rh_unidad_org` INT NOT NULL,
	`userid` VARCHAR(32) NOT NULL
);
CREATE UNIQUE INDEX `gop_presupuesto_id` ON `gop_presupuesto` (`ref_unidad`, `ejercicio`);
CREATE UNIQUE INDEX `gop_usuario_uo_id` ON `gop_usuario_uo` (`ref_rh_unidad_org`, `userid`);
ALTER TABLE `rh_unidad_org` ADD FOREIGN KEY (`superior`) REFERENCES `rh_unidad_org`(`sys_pk`);
ALTER TABLE `gop_presupuesto` ADD FOREIGN KEY (`ref_unidad`) REFERENCES `rh_unidad_org`(`sys_pk`);
ALTER TABLE `gop_presupuesto` ADD FOREIGN KEY (`status`) REFERENCES `gop_presupuesto_status`(`id`);
ALTER TABLE `gop_presupuesto` ADD FOREIGN KEY (`divisa`) REFERENCES `divisa`(`sys_pk`);
ALTER TABLE `gop_partida` ADD FOREIGN KEY (`ref_presupuesto`) REFERENCES `gop_presupuesto`(`sys_pk`);
ALTER TABLE `gop_partida` ADD FOREIGN KEY (`padre`) REFERENCES `gop_partida`(`sys_pk`);
ALTER TABLE `gop_usuario_uo` ADD FOREIGN KEY (`ref_rh_unidad_org`) REFERENCES `rh_unidad_org`(`sys_pk`);
